Traceback (most recent call last):
  File "C:\Users\sss0031\AppData\Local\miniforge3\envs\opy\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\sss0031\AppData\Local\miniforge3\envs\opy\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\sss0031\AppData\Local\miniforge3\envs\opy\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\sss0031\AppData\Local\miniforge3\envs\opy\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\sss0031\AppData\Local\miniforge3\envs\opy\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\sss0031\AppData\Local\miniforge3\envs\opy\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\sss0031\AppData\Local\miniforge3\envs\opy\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Connect to Aspen Plus
aspen = win32com.client.Dispatch('Apwn.Document')

# Load the simulation file
simulation_path = r"G:\My Drive\doutorado\gasifier\20250324\aspen_files\20250324_2.apw"
aspen.InitFromArchive2(simulation_path)
aspen.Visible = 1  # Make Aspen visible
aspen.SuppressDialogs = 1  # Suppress dialog pop-ups

print("Connected to Aspen Plus successfully")
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mcom_error[0m                                 Traceback (most recent call last)
File [1;32m~\AppData\Local\miniforge3\envs\opy\lib\site-packages\win32com\client\dynamic.py:84[0m, in [0;36m_GetGoodDispatch[1;34m(IDispatch, clsctx)[0m
[0;32m     83[0m [38;5;28;01mtry[39;00m:
[1;32m---> 84[0m     IDispatch [38;5;241m=[39m [43mpythoncom[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43mIDispatch[49m[43m)[49m
[0;32m     85[0m [38;5;28;01mexcept[39;00m pythoncom[38;5;241m.[39mole_error:

[1;31mcom_error[0m: (-2147221005, 'Invalid class string', None, None)

During handling of the above exception, another exception occurred:

[1;31mcom_error[0m                                 Traceback (most recent call last)
Cell [1;32mIn[2], line 2[0m
[0;32m      1[0m [38;5;66;03m# Connect to Aspen Plus[39;00m
[1;32m----> 2[0m aspen [38;5;241m=[39m [43mwin32com[49m[38;5;241;43m.[39;49m[43mclient[49m[38;5;241;43m.[39;49m[43mDispatch[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mApwn.Document[39;49m[38;5;124;43m'[39;49m[43m)[49m
[0;32m      4[0m [38;5;66;03m# Load the simulation file[39;00m
[0;32m      5[0m simulation_path [38;5;241m=[39m [38;5;124mr[39m[38;5;124m"[39m[38;5;124mG:[39m[38;5;124m\[39m[38;5;124mMy Drive[39m[38;5;124m\[39m[38;5;124mdoutorado[39m[38;5;124m\[39m[38;5;124mgasifier[39m[38;5;124m\[39m[38;5;124m20250324[39m[38;5;124m\[39m[38;5;124maspen_files[39m[38;5;124m\[39m[38;5;124m20250324_2.apw[39m[38;5;124m"[39m

File [1;32m~\AppData\Local\miniforge3\envs\opy\lib\site-packages\win32com\client\__init__.py:118[0m, in [0;36mDispatch[1;34m(dispatch, userName, resultCLSID, typeinfo, UnicodeToString, clsctx)[0m
[0;32m    116[0m [38;5;250m[39m[38;5;124;03m"""Creates a Dispatch based COM object."""[39;00m
[0;32m    117[0m [38;5;28;01massert[39;00m UnicodeToString [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m, [38;5;124m"[39m[38;5;124mthis is deprecated and will go away[39m[38;5;124m"[39m
[1;32m--> 118[0m dispatch, userName [38;5;241m=[39m [43mdynamic[49m[38;5;241;43m.[39;49m[43m_GetGoodDispatchAndUserName[49m[43m([49m[43mdispatch[49m[43m,[49m[43m [49m[43muserName[49m[43m,[49m[43m [49m[43mclsctx[49m[43m)[49m
[0;32m    119[0m [38;5;28;01mreturn[39;00m __WrapDispatch(dispatch, userName, resultCLSID, typeinfo, clsctx[38;5;241m=[39mclsctx)

File [1;32m~\AppData\Local\miniforge3\envs\opy\lib\site-packages\win32com\client\dynamic.py:104[0m, in [0;36m_GetGoodDispatchAndUserName[1;34m(IDispatch, userName, clsctx)[0m
[0;32m    101[0m     [38;5;66;03m## ??? else userName remains None ???[39;00m
[0;32m    102[0m [38;5;28;01melse[39;00m:
[0;32m    103[0m     userName [38;5;241m=[39m [38;5;28mstr[39m(userName)
[1;32m--> 104[0m [38;5;28;01mreturn[39;00m ([43m_GetGoodDispatch[49m[43m([49m[43mIDispatch[49m[43m,[49m[43m [49m[43mclsctx[49m[43m)[49m, userName)

File [1;32m~\AppData\Local\miniforge3\envs\opy\lib\site-packages\win32com\client\dynamic.py:86[0m, in [0;36m_GetGoodDispatch[1;34m(IDispatch, clsctx)[0m
[0;32m     84[0m         IDispatch [38;5;241m=[39m pythoncom[38;5;241m.[39mconnect(IDispatch)
[0;32m     85[0m     [38;5;28;01mexcept[39;00m pythoncom[38;5;241m.[39mole_error:
[1;32m---> 86[0m         IDispatch [38;5;241m=[39m [43mpythoncom[49m[38;5;241;43m.[39;49m[43mCoCreateInstance[49m[43m([49m
[0;32m     87[0m [43m            [49m[43mIDispatch[49m[43m,[49m[43m [49m[38;5;28;43;01mNone[39;49;00m[43m,[49m[43m [49m[43mclsctx[49m[43m,[49m[43m [49m[43mpythoncom[49m[38;5;241;43m.[39;49m[43mIID_IDispatch[49m
[0;32m     88[0m [43m        [49m[43m)[49m
[0;32m     89[0m [38;5;28;01melse[39;00m:
[0;32m     90[0m     [38;5;66;03m# may already be a wrapped class.[39;00m
[0;32m     91[0m     IDispatch [38;5;241m=[39m [38;5;28mgetattr[39m(IDispatch, [38;5;124m"[39m[38;5;124m_oleobj_[39m[38;5;124m"[39m, IDispatch)

[1;31mcom_error[0m: (-2147221005, 'Invalid class string', None, None)

